### ISSUE TITLE
Docker build failing?

### ISSUE THREAD

**Issue by DbCrWk** [nborrmann/diff-poetry-lock#16]
This action is great! However, this action just stopped running due to some (cryptic) Docker failure. I wonder if it's related to the [release of Poetry 2](https://github.com/python-poetry/poetry/commit/8cad7a423b459871e9ed6094252b15c9ddb8a7dd)?

## Our Action YAML File

```yaml
name: Poetry Diff
on: [pull_request]

jobs:
    poetry-dff:
        runs-on: ubuntu-latest
        steps:
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}

            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Poetry
              run: |
                  pipx install poetry==1.8.3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.10.12
                  cache: poetry

            - name: Poetry Diff
              uses: nborrmann/diff-poetry-lock@main
```

## Build Log from Github Action Run
[2_Build nborrmann_diff-poetry-lock@main.txt](https://github.com/user-attachments/files/18321990/2_Build.nborrmann_diff-poetry-lock%40main.txt)
