### ISSUE TITLE
Consider using a prebuild docker image that is publicly available

### ISSUE THREAD

**Issue by dpelengic** [nborrmann/diff-poetry-lock#9]
Currently, this action (pre)builds the action docker image on each run, meaning it also pulls the base images each time. In our case, this lead us to hit the dockerhub rate limits.

Consider pre-building the action and hosting it in a public repo. This should also improve the overall speed of the action, as docker pulls should be faster than builds.

Something like this:
```yaml
# action.yaml
...
runs:
  using: 'docker'
  image: 'docker://your-public-docker-repo/diff-poetry-lock:main'
```
